### PR TITLE
Propose asciidoctor usage

### PR DESCRIPTION
**Pull request by mathisloge**
I would like to propose the writing with the asciidoctor ruby package. 
In my opinion it is better readable. 

I've added the github workflow actions to deploy the site directly. 

You can view the html result here: [https://mathisloge.github.io/CommsDSL-Specification](https://mathisloge.github.io/CommsDSL-Specification)

### CODE REVIEW

**Comment by arobenko** [comment]
Hi Mathis,
The web page does look prettier. Sorry, but I'm not a ruby user. In order to be able to migrate to ruby I need the following:
- Make it buildable on my Linux PC as cmake target (separate instructions on how to prepare the ruby environment are also needed).
- Have PDF build in addition to html. Does the ruby environment support PDF generation as well? Is it prettier? 
- Avoid automatic deploy to github pages. I prefer to do it manually. It's not a continuous integration process.
- Have the pull request to be on separate "feature" branch which can be reviewed and tested before merging it to master (which in my workflow always points to the latest release). 

Thanks

**Comment by mathisloge** [comment]
Hi Alex,

I have added some installation instructions to the readme file. I hope that they provide you with the information you need. 
The cmake targets have not changed. 

I've removed the autodeploy target. 

For the featurebranch: can you create a new branch? I can't create an other branch. 

Generated pdf by the ruby enviroment:
[commsdsl_spec.pdf](https://github.com/commschamp/CommsDSL-Specification/files/5403593/commsdsl_spec.pdf)

**Comment by arobenko** [comment]
The PDF also looks pretty, the coloring helps to catch the missing quotes (") around the values.
I'll try to take a closer look at this in the next several days or a weekend.
Thanks

**Comment by arobenko** [comment]
Hi Mathis,
I'm trying out your pull request now. The `asciidoctor` and `asciidoctor-pdf` weere successfully installed as my local gems. The PDF is built fine using the installed gem 
```
$> which asciidoctor-pdf
/home/alex/gems/bin/asciidoctor-pdf
```
However when I try to build `site` target I get the following error:
```
$> make site
Traceback (most recent call last):
        1: from /home/alex/gems/bin/asciidoctor:23:in `<main>'
/home/alex/gems/bin/asciidoctor:23:in `load': cannot load such file -- /usr/share/rubygems-integration/all/gems/asciidoctor-2.0.10/bin/asciidoctor (LoadError
```
Isn't the local gem supposed to invoke `/usr/bin/asciidoctor`? Why does the `asciidoctor-pdf` work fine, but `asciidoctor` doesn't? What am I missing here? 
```
$> which asciidoctor
/home/alex/gems/bin/asciidoctor
```

**Comment by arobenko** [comment]
It looks like if I invoke `/usr/bin/asciidoctor` directly everything works fine. Do I actually need the local gems?

**Comment by mathisloge** [comment]
might be possible, that `find_program (ASCIIDOCTOR_EXE asciidoctor)`  gets confused with multiple installations. 
What is the output of `gem which asciidoctor`  and `gem which asciidoctor-pdf` ?

**Comment by arobenko** [comment]
Forget it, I uninstalled the local gems and `/usr/bin/asciidoctor` as well as `/usr/bin/asciidoctor-pdf` take over now. Everything seems to be working.
I've merged your pull request to `develop` branch. I will go over the whole spec again and fix the missing (") in XML code examples where the coloring is wrong. I will merge it to master and do the next v3.1.3 release during the weekend or early next week.

**Comment by mathisloge** [comment]
super. I'm glad I could help. 👍 

should i close this PR since it is merged?

**Pull request merged**
